[package]
name = "sidekiq-warp"
version = "0.1.0"
authors = ["Dax Huiberts <daxhuiberts@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "*", features = ["derive"] }
sidekiq-lib = { path = "../sidekiq-lib" }
tera = { version = "*", default-features = false }
tokio = "*"
warp = "*"
